### ISSUE TITLE
12 remove fsm_location.billing_id from fieldservice module

### ISSUE THREAD

**Issue by hparfr** [OCA/field-service#331]
On the main module, there is this required field : 
```py
class FSMLocation(models.Model):
...
    customer_id = fields.Many2one('res.partner', string='Billed Customer',
                                  required=True, ondelete='restrict',
                                  auto_join=True,
                                  track_visibility='onchange')
```
https://github.com/OCA/field-service/blob/12.0/fieldservice/models/fsm_location.py#L19

I propose to move this field out of the main module because it's not generic enough.

The billing customer can come from: 
- sale
- agreements
- contracts ?
- project ?

And the same location can be billed to different customers. Like the owner of the walls and the tenant can be both billed.

**Comment by brian10048** [comment]
Sales, Agreements, Contracts, and Projects might all need to use the customer_id field so to me it would seem necessary to have this field in the base module.

A compromise might be to remove the required attribute in the base module.

@max3903 @wolfhall Your thoughts?

**Comment by max3903** [comment]
Ping @patrickrwilson

**Comment by max3903** [comment]
I believe we can move this field to the fieldservice_account module as this is where we generate a customer invoice from the FSM order.

**Comment by patrickrwilson** [comment]
I agree with @max3903 that this field should probably should live in the fieldservice_account module since it is used in the accounting part of field service. I like to think of this field as the 'default' billing contact. It is true that multiple customers could be billed but if we bill the location itself, this field gives the ability to specify who the billing contact is. We use this heavily in our business as the owner isn't always who gets the invoice.

**Comment by hparfr** [comment]
Great. Do you prefer one big PR or one per module ?

**Comment by max3903** [comment]
One per module please. Thank you.
