### ISSUE TITLE
[RFC] Customer on Location/Order

### ISSUE THREAD

**Issue by max3903** [OCA/field-service#524]
Sorry to bring the subject back again but I have a requirement to have the customer information on the location and order.

My scenario is that the FSM order is created from the Sale Order validation and the worker needs to have the customer info in addition to the location.

What do you think of:

- [ ] extracting the customer_id field from `fieldservice_account_analytic` but leaving the invoice generation logic
- [ ]  adding it back to `fieldservice_account`

CC: @brian10048 @hparfr @osi-scampbell @wolfhall @rto-odoo

**Comment by brian10048** [comment]
This is not a problem for me.

@hparfr was more concerned about the placement of the customer_id field from what I remember

**Comment by hparfr** [comment]
1)Yes, it was very confusing for multiple customers. Location is enough for most of the cases. 
2) Plus I asked to remove billing id because there was some logic about it. It was not the responsibility of the FSM Order to manage the billing.
3) You can have multiple customers with the same location (the owner / the renter). So binding locations to customers can be wrong.


I can understand the worker needs the name of the client on the Order, but why in the location too?

**Comment by max3903** [comment]
@hparfr 

1) customer_id is not required on FSM order, so you should be fine here.
2) The logic to invoice from a FSM order is not in `fieldservice_account`, so we're good.
3) The location has multiple fields to store the owner, the customer, the contact.

> I can understand the worker needs the name of the client on the Order, but why in the location too?

Because a FSM order can be created manually and the worker needs to know the customer. 

What do you think of renaming the field "Customer" on the location to "Default Customer"? Would that work for your scenario?

**Comment by hparfr** [comment]
Ok, then I will hide all theses fields in a new (custom?) module.

Usually, the base module should be generic and other modules adds features, not remove them.

**Comment by hparfr** [comment]
You don't use field_account_analyitic for this projetct ?

**Comment by max3903** [comment]
@hparfr 

No, this is a delivery service where customer calls, requests X products. Products gets invoiced before delivery. When the products is delivered to the location (address), customer pays.

The location name is the address in the form of "1, Main Drive". No customer name...

What do you think of adding a checkbox in the settings to show the customer_id field using a specific group? Field can be hidden by default until you check the box in the settings. Would that work for you?

**Comment by osi-scampbell** [comment]
@max3903 It looks like I am a day late to this discussion, I agree with moving the customer_id field back to the fieldservice_account module and I think it should be visible on the FSO. I don't think we should change the name from "Customer" to "Default Customer" because isn't that already implied? I believe the users will assume the "Customer" fields is the Default Customer. 

I think @hparfr brings up a good point in keeping the base modules as generic as possible and we don't have the best solution for capturing the owner/tenant relationship which is a pretty common occurrance. Can we handle this the same way we handle billing customer vs billing location. We just add another selection for "Bill Owner".

**Comment by hparfr** [comment]
@osi-scampbell My point is that a location should be (as much as possible) free.
Owner, Tenant is just a point of view in a particular context and is not generic.
The partner info should be available on the FSM Order (directly, or from a link to a SO).

>Because a FSM order can be created manually and the worker needs to know the customer.

@max3903 May be this should not be allowed for your use case. In my opinon FSM should be consistent with says delivery: if you create a delivery order by itself, you don't have the customer.

If you definitely want it, you can do a late binding: first let the user create a FSM Order then, with a wizard, create a sale order and bind it to the FSM Order. 
For instance, you can have a look how purchase_request let you bind a purchase request line to a new or existing purchase order.
