### ISSUE TITLE
Bug: FSM Location is not set to the selected Delivery address

### ISSUE THREAD

**Issue by dreispt** [OCA/field-service#547]
1. Create an SO
2. Select the Customer. This autodfills Invoicing Address, Shipping Address and FSM Location.
3. Select a different Shipping address. The FSM Location stays the Customer Address. I expected it to change to the Shipping address.

I expect the Shipping address to correspond to the service address in an FSM scenario, so the FSM Location should match the selected Shipping Address.

I wonder if the SO FSM Location can't be implemented as a computed field. This would skip entirely the need to rely on onchange mechanisms.

**Comment by max3903** [comment]
The FSM location defaults to:

* the partner
* the shipping address
* the commercial partner

if they are FSM locations.

In your case, it looks like the partner is also a FSM location so it doesn't change.

The computed field would not work because you can have many FSM locations behind one delivery address. (if you want to ship to your kitchen and living room, same address to ship to but different locations)

**Comment by dreispt** [comment]
> The computed field would not work because you can have many FSM locations 

Good point.

> In your case, it looks like the partner is also a FSM location so it doesn't change.

The more general Partner should not overshadow the more specific Shipping/Delivery address.
So if both have FSM Locations, the second should prevail over the first.

**Comment by max3903** [comment]
@brian10048 Do you agree?

**Comment by brian10048** [comment]
It does seem that changing the shipping/delivery address should update the service location in most cases.

So we would default the FSM location to this order instead?

- shipping address
- partner
- commercial partner

**Comment by max3903** [comment]
Works for me.
