### ISSUE TITLE
complete location name not set

### ISSUE THREAD

**Issue by babatoko** [OCA/field-service#640]
Location complete name is not set when converting contact

how to reproduce:
1. go to a contact details
2. select "convert to FSM Record" menu
3. select location and validate
then
4. go to location into Master data
5. look at the newly record and the complete name is not set

not sure how to provide more details

cheers

**Comment by babatoko** [comment]
This issue couldn't be test on runbot because there is an "API key for GeoCoding (Places) required" issue.

**Comment by dalonsod** [comment]
Hi @babatoko I've reproduced the issue creating a location with only the required fields filled. The location is created, `complete_name` is unset. Then, it's not possible to select any location across the application because there's one record with this problem.

If you look at this code
https://github.com/OCA/field-service/blob/12.0/fieldservice/models/fsm_location.py#L65-L80

you'll see `name` field is missing (`partner_id.name` is used instead), I suspect the problem is with this field (compute method should not be fired because `partner_id.name` doesn't fire it, at least during the `fsm.location` creation).

@max3903 what do you think, `name` should also be added to `@api.depends` for `_compute_complete_name` method of `fsm.location`?

**Comment by babatoko** [comment]
Hi @dalonsod Great to hear that you've reproduce. Half of the fix is done ;-)

cheers
