### ISSUE TITLE
Required field "Related Partner" cannot be populated when creating location

### ISSUE THREAD

**Issue by bloke-in-kent** [OCA/field-service#683]
This is also the case when trying to create a worker. The field label is there but no form element to populate it.

This is a fresh install of odoo 12 on Ubuntu 20.04. I've tried installing the fieldservice_partner_multi_relation app to see if that helps, but always returns an error:

File "src/lxml/etree.pyx", line 3631, in lxml.etree._Validator.assert_
AssertionError: Element odoo has extra content: record, line 3

And I tried installing partner_multi_relation app which gives the same error.

I'm new to odoo so am pretty stuck on this. Thanks

**Comment by tarbib** [comment]
Hello,

Actually I noticed the same issue, I think.

The field related partner is read only and not populated leading to the impossibility to create a new location.

https://user-images.githubusercontent.com/2255433/105328821-bf8dd280-5bd0-11eb-86d2-4690c9d99d2d.mp4

Maybe it should not be read only?

**Comment by HekkiMelody** [comment]
I'm having the same problem. 

As a workaround, setting required to False for partner_id in the views seems to work, and the field is then populated on creation as expected.

**Comment by pleirb** [comment]
The exact same thing happens to me

**Comment by pleirb** [comment]
In principle what I did in debugger mode edit the formulaio view and remove groups = "base.group_no_one" readonly = "1" from the partner_id tag

**Comment by pleirb** [comment]
This error is repeated in several parts, for example the person. Something is missing

**Comment by humandevs** [comment]
As a note, if you remove the readonly = "1" section from the view, it will show a Partner selection field on the form. This is bad because if a user then selects an existing Contact/partner from the dropdown and then changes the Title of that 'partner', it will change the Title of that 'partner' record throughout Odoo, thus changing the name of that Contact/Partner record, even if that record is the myCompany record, which is probably not what you want! Instead, removing the 'required' type of the field in the model is probably the way to go here.
